### ISSUE TITLE
share-scenario-do.php doesn't require user to be logged in

### ISSUE THREAD

**Issue by tylerthetiger** [airmencoders/hawgops#1]
public_html/do/share-scenario-do.php doesn't require user to be logged in to use.  It would be possible for spam to be sent to any user.

For example: curl https://hawg-ops.com/do/share-scenario-do -d "scenario-name=ThisIsWhereIwouldPutMySpamMessageIfIwereSpammer&share-scenario-id=1234&email-share=AnyRecipientYouWant@gmail.com" -k --verbose
would result in an email message being sent.  

Additionally, should probably require that the recipient actually has an account before allowing the message to be sent.

**Comment by chris-m92** [comment]
Thanks man, Definitely something that was erroneously overlooked. Thankfully nothing has really noticed the /do directory and hasn't spammed out anything. But now it requires that a user is logged in to do so.

Fixed in commit c9bd61b

As far as your other comment regarding that the recipient has an account, when I initially made this feature I tossed and turned regarding that requirement and ultimately decided against it. This is because I've seen the amount of users on the website as well as the traffic and I've seen plenty of times where an instructor has sent a scenario to somebody that doesn't have an account in order to share the next day's mission planning with them.

Granted, the next step of them actually reviewing the scenario requires them to have an account. Either way, they would either receive an email saying someone has a scenario for them or they receive an email saying here's the scenario, oops you don't have an account. 

Either way I can definitely clean that up.
